[tool.poetry]
name = "valthera-core"
version = "0.1.0"
description = "Core utilities and shared code for Valthera Lambda functions"
authors = ["Valthera Team"]
readme = "README.md"
packages = [{include = "valthera_core"}]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.34.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
black = "^23.0.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 